laravel/app/routes.php
<?php

Route::any('/', array('as' => 'home', 'uses' => 'HomeController@index'));
Route::any('home', array('as' => 'home', 'uses' => 'HomeController@index'));
Route::any('comerciante', array('as' => 'comerciante', 'uses' => 'HomeController@comerciante'));
Route::any('termos-de-uso', array('as' => 'termos', 'uses' => 'HomeController@termosDeUso'));
Route::post('enviaContatoVisitantes', array('as' => 'contato.visitantes', 'uses' => 'HomeController@enviaContatoVisitantes'));
Route::post('enviaContatoEmpresa', array('as' => 'contato.empresas', 'uses' => 'HomeController@enviaContatoEmpresa'));
Route::post('cadastraNewsletter', array('as' => 'cadastro.newsletter', 'uses' => 'HomeController@cadastraNewsletter'));

Route::get('painel', array('before' => 'auth', 'as' => 'painel.home', 'uses' => 'Painel\HomeController@index'));
Route::get('painel/login', array('as' => 'painel.login', 'uses' => 'Painel\HomeController@login'));

// Autenticação do Login
Route::post('painel/login',  array('as' => 'painel.auth', function(){
	$authvars = array(
		'username' => Input::get('username'),
		'password' => Input::get('password')
	);

	$lembrar = (Input::get('lembrar') == '1') ? true : false;

	if(Auth::attempt($authvars, $lembrar)){
		return Redirect::to('painel');
	}else{
		Session::flash('login_errors', true);
		return Redirect::to('painel/login');
	}
}));

Route::get('painel/logout', array('as' => 'painel.off', function(){
	Auth::logout();
	return Redirect::to('painel');
}));

Route::post('ajax/gravaOrdem', array('before' => 'auth', 'uses' => 'Painel\AjaxController@gravaOrdem'));

Route::group(array('prefix' => 'painel', 'before' => 'auth'), function()
{

    Route::get('download', function(){

    	$filename = 'cadastros_'.date('d-m-Y-H-i-s');

		Excel::create($filename, function($excel) {
		    $excel->sheet('Usuários Cadastrados', function($sheet) {
		        $sheet->fromModel(\CadastrosNewsletter::select('nome', 'email')->orderBy('nome')->get());
		    });
		})->download('csv');
    });
    	
    Route::resource('usuarios', 'Painel\UsuariosController');
    Route::resource('banner', 'Painel\BannerController');
	Route::resource('sobre', 'Painel\SobreController');
	Route::resource('comofunciona', 'Painel\ComoFuncionaController');
	Route::resource('vantagens', 'Painel\VantagensController');
	Route::resource('comerciante', 'Painel\ComercianteController');
	Route::resource('pelasuaempresa', 'Painel\PelaSuaEmpresaController');
	Route::resource('pelasuaempresavantagens', 'Painel\PelaSuaEmpresaVantagensController');
	Route::resource('contato', 'Painel\ContatoController');
	Route::resource('termosdeuso', 'Painel\TermosDeUsoController');
	Route::resource('contatosvisitantes', 'Painel\ContatosVisitantesController');
	Route::resource('contatosempresas', 'Painel\ContatosEmpresasController');
	Route::resource('cadastrosnewsletter', 'Painel\CadastrosNewsletterController');
	Route::resource('seo', 'Painel\SEOController');
	Route::resource('links', 'Painel\LinksController');
	//NOVASROTASDOPAINEL//
});

laravel/app/models/PelaSuaEmpresaVantagens.php
<?php

class PelaSuaEmpresaVantagens extends Eloquent
{

	/**
	 * The database table used by the model.
	 *
	 * @var string
	 */
	protected $table = 'pela_sua_empresa_vantagens';

	/**
	 * The attributes excluded from the model's JSON form.
	 *
	 * @var array
	 */
	protected $hidden = array();

	// array of attributes we CAN set on the backend
    protected $fillable = array('', 'created_at', 'updated_at');

    // and those we CAN'T set on the backend
    protected $guarded = array('id');

    public function scopeOrdenado($query)
    {
    	return $query->orderBy('ordem', 'asc')->get();
    }
}

laravel/app/controllers/painel/PelaSuaEmpresaVantagensController.php
<?php

namespace Painel;

use \View, \Input, \Str, \Session, \Redirect, \Hash, \Thumb, \Tools, \File, PelaSuaEmpresaVantagens;

class PelaSuaEmpresaVantagensController extends BaseAdminController {

	protected $layout = 'backend.templates.index';

	protected $limiteInsercao = false;

	/**
	 * Display a listing of the resource.
	 *
	 * @return Response
	 */
	public function index()
	{
		$this->layout->content = View::make('backend.pelasuaempresavantagens.index')->with('registros', PelaSuaEmpresaVantagens::orderBy('ordem', 'ASC')->get());		
	}

	/**
	 * Show the form for creating a new resource.
	 *
	 * @return Response
	 */
	public function create()
	{
		$this->layout->content = View::make('backend.pelasuaempresavantagens.form');
	}

	/**
	 * Store a newly created resource in storage.
	 *
	 * @return Response
	 */
	public function store()
	{
		$object = new PelaSuaEmpresaVantagens;

		$object->texto = Input::get('texto');



		
		try {

			$object->save();

			Session::flash('sucesso', true);
			Session::flash('mensagem', 'Vantagem criado com sucesso.');
			return Redirect::route('painel.pelasuaempresavantagens.index');

		} catch (\Exception $e) {

			Session::flash('formulario', Input::all());
			return Redirect::back()->withErrors(array('Erro ao criar Vantagem!'));	

		}		
	}

	/**
	 * Display the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function show($id)
	{
	}

	/**
	 * Show the form for editing the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function edit($id)
	{
		$this->layout->content = View::make('backend.pelasuaempresavantagens.edit')->with('registro', PelaSuaEmpresaVantagens::find($id));
	}

	/**
	 * Update the specified resource in storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function update($id)
	{
		$object = PelaSuaEmpresaVantagens::find($id);

		$object->texto = Input::get('texto');


		try {

			$object->save();
			Session::flash('sucesso', true);
			Session::flash('mensagem', 'Vantagem alterado com sucesso.');
			return Redirect::route('painel.pelasuaempresavantagens.index');

		} catch (\Exception $e) {

			Session::flash('formulario', Input::all());
			return Redirect::back()->withErrors(array('Erro ao criar Vantagem!'));

		}
	}

	/**
	 * Remove the specified resource from storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function destroy($id)
	{
		$object = PelaSuaEmpresaVantagens::find($id);
		$object->delete();

		Session::flash('sucesso', true);
		Session::flash('mensagem', 'Vantagem removido com sucesso.');

		return Redirect::route('painel.pelasuaempresavantagens.index');
	}

}

laravel/app/views/backend/pelasuaempresavantagens/edit.blade.php
@section('conteudo')

    <div class="container add">

      	<h2>
        	Editar Vantagem
        </h2>  

		{{ Form::open( array('route' => array('painel.pelasuaempresavantagens.update', $registro->id), 'files' => true, 'method' => 'put') ) }}
			<div class="pad">

		    	@if(Session::has('sucesso'))
		    	   <div class="alert alert-block alert-success"><button type="button" class="close" data-dismiss="alert">&times;</button>{{ Session::get('mensagem') }}</div>
		        @endif

		    	@if($errors->any())
		    		<div class="alert alert-block alert-danger"><button type="button" class="close" data-dismiss="alert">&times;</button>{{ $errors->first() }}</div>
		    	@endif	


				<div class="form-group">
					<label for="inputTexto">Texto</label>
					<input type="text" class="form-control" id="inputTexto" name="texto" value="{{$registro->texto}}" required>
				</div>
				

				<button type="submit" title="Salvar" class="btn btn-success">Salvar</button>

				<a href="{{URL::route('painel.pelasuaempresavantagens.index')}}" title="Voltar" class="btn btn-default btn-voltar">Voltar</a>

			</div>
		</form>
    </div>
    
@stop

laravel/app/views/backend/pelasuaempresavantagens/form.blade.php
@section('conteudo')

    <div class="container add">

      	<h2>
        	Adicionar Vantagem
        </h2>  

		<form action="{{URL::route('painel.pelasuaempresavantagens.store')}}" method="post" enctype="multipart/form-data">
			<div class="pad">

		    	@if(Session::has('sucesso'))
		    	   <div class="alert alert-block alert-success"><button type="button" class="close" data-dismiss="alert">&times;</button>{{ Session::get('mensagem') }}</div>
		        @endif

		    	@if($errors->any())
		    		<div class="alert alert-block alert-danger"><button type="button" class="close" data-dismiss="alert">&times;</button>{{ $errors->first() }}</div>
		    	@endif


				<div class="form-group">
					<label for="inputTexto">Texto</label>
					<input type="text" class="form-control" id="inputTexto" name="texto" @if(Session::has('formulario')) value="{{ $s=Session::get('formulario'); echo $s['texto'] }}" @endif required>
				</div>
				

				<button type="submit" title="Inserir" class="btn btn-success">Inserir</button>

				<a href="{{URL::route('painel.pelasuaempresavantagens.index')}}" title="Voltar" class="btn btn-default btn-voltar">Voltar</a>

			</div>
		</form>
    </div>
    
@stop

laravel/app/views/backend/pelasuaempresavantagens/index.blade.php
@section('conteudo')

<div class="container">

    @if(Session::has('sucesso'))
        <div class="alert alert-block alert-success"><button type="button" class="close" data-dismiss="alert">&times;</button>{{ Session::get('mensagem') }}</div>
    @endif

    @if($errors->any())
        <div class="alert alert-block alert-danger"><button type="button" class="close" data-dismiss="alert">&times;</button>{{ $errors->first() }}</div>
    @endif

    <h2>
        Pela Sua Empresa - Vantagens <a href='{{ URL::route('painel.pelasuaempresavantagens.create') }}' class='btn btn-success btn-sm pull-right'><span class='glyphicon glyphicon-plus-sign'></span> Adicionar Vantagem</a>
    </h2>

    <table class='table table-striped table-bordered table-hover table-sortable' data-tabela='pela_sua_empresa_vantagens'>

        <thead>
            <tr>
                <th>Ordenar</th>
				<th>Texto</th>
                <th><span class="glyphicon glyphicon-cog"></span></th>
            </tr>
        </thead>

        <tbody>
        @foreach ($registros as $registro)

            <tr class="tr-row" id="row_{{ $registro->id }}">
                <td class='move-actions'><a href='#' class='btn btn-info btn-move btn-sm'>mover</a></td>
				<td>{{ $registro->texto }}</td>
                <td class="crud-actions">
                    <a href='{{ URL::route('painel.pelasuaempresavantagens.edit', $registro->id ) }}' class='btn btn-primary btn-sm'>editar</a>
						{{ Form::open(array('route' => array('painel.pelasuaempresavantagens.destroy', $registro->id), 'method' => 'delete')) }}
							<button type='submit' class='btn btn-danger btn-sm btn-delete'>excluir</button>
						{{ Form::close() }}                    
                </td>
            </tr>

        @endforeach
        </tbody>

    </table>

    
</div>

@stop