laravel/app/routes.php
<?php

Route::any('/', array('as' => 'home', 'uses' => 'HomeController@index'));
Route::any('home', array('as' => 'home', 'uses' => 'HomeController@index'));
Route::any('comerciante', array('as' => 'comerciante', 'uses' => 'HomeController@comerciante'));
Route::any('termos-de-uso', array('as' => 'termos', 'uses' => 'HomeController@termosDeUso'));
Route::post('enviaContatoVisitantes', array('as' => 'contato.visitantes', 'uses' => 'HomeController@enviaContatoVisitantes'));
Route::post('enviaContatoEmpresa', array('as' => 'contato.empresas', 'uses' => 'HomeController@enviaContatoEmpresa'));
Route::post('cadastraNewsletter', array('as' => 'cadastro.newsletter', 'uses' => 'HomeController@cadastraNewsletter'));

Route::get('painel', array('before' => 'auth', 'as' => 'painel.home', 'uses' => 'Painel\HomeController@index'));
Route::get('painel/login', array('as' => 'painel.login', 'uses' => 'Painel\HomeController@login'));

// Autenticação do Login
Route::post('painel/login',  array('as' => 'painel.auth', function(){
	$authvars = array(
		'username' => Input::get('username'),
		'password' => Input::get('password')
	);

	$lembrar = (Input::get('lembrar') == '1') ? true : false;

	if(Auth::attempt($authvars, $lembrar)){
		return Redirect::to('painel');
	}else{
		Session::flash('login_errors', true);
		return Redirect::to('painel/login');
	}
}));

Route::get('painel/logout', array('as' => 'painel.off', function(){
	Auth::logout();
	return Redirect::to('painel');
}));

Route::post('ajax/gravaOrdem', array('before' => 'auth', 'uses' => 'Painel\AjaxController@gravaOrdem'));

Route::group(array('prefix' => 'painel', 'before' => 'auth'), function()
{

    Route::get('download', function(){

    	$filename = 'cadastros_'.date('d-m-Y-H-i-s');

		Excel::create($filename, function($excel) {
		    $excel->sheet('Usuários Cadastrados', function($sheet) {
		        $sheet->fromModel(\CadastrosNewsletter::select('nome', 'email')->orderBy('nome')->get());
		    });
		})->download('csv');
    });
    	
    Route::resource('usuarios', 'Painel\UsuariosController');
    Route::resource('banner', 'Painel\BannerController');
	Route::resource('sobre', 'Painel\SobreController');
	Route::resource('comofunciona', 'Painel\ComoFuncionaController');
	Route::resource('vantagens', 'Painel\VantagensController');
	Route::resource('comerciante', 'Painel\ComercianteController');
	Route::resource('pelasuaempresa', 'Painel\PelaSuaEmpresaController');
	Route::resource('pelasuaempresavantagens', 'Painel\PelaSuaEmpresaVantagensController');
	Route::resource('contato', 'Painel\ContatoController');
	Route::resource('termosdeuso', 'Painel\TermosDeUsoController');
	Route::resource('contatosvisitantes', 'Painel\ContatosVisitantesController');
	Route::resource('contatosempresas', 'Painel\ContatosEmpresasController');
	Route::resource('cadastrosnewsletter', 'Painel\CadastrosNewsletterController');
	Route::resource('seo', 'Painel\SEOController');
	Route::resource('links', 'Painel\LinksController');
	//NOVASROTASDOPAINEL//
});

laravel/app/models/Vantagens.php
<?php

class Vantagens extends Eloquent
{

	/**
	 * The database table used by the model.
	 *
	 * @var string
	 */
	protected $table = 'vantagens';

	/**
	 * The attributes excluded from the model's JSON form.
	 *
	 * @var array
	 */
	protected $hidden = array();

	// array of attributes we CAN set on the backend
    protected $fillable = array('', 'created_at', 'updated_at');

    // and those we CAN'T set on the backend
    protected $guarded = array('id');

}

laravel/app/controllers/painel/VantagensController.php
<?php

namespace Painel;

use \View, \Input, \Str, \Session, \Redirect, \Hash, \Thumb, \Tools, \File, Vantagens;

class VantagensController extends BaseAdminController {

	protected $layout = 'backend.templates.index';

	protected $limiteInsercao = '1';

	/**
	 * Display a listing of the resource.
	 *
	 * @return Response
	 */
	public function index()
	{
		$this->layout->content = View::make('backend.vantagens.index')->with('registros', Vantagens::all())->with('limiteInsercao', $this->limiteInsercao);		
	}

	/**
	 * Show the form for creating a new resource.
	 *
	 * @return Response
	 */
	public function create()
	{
		$this->layout->content = View::make('backend.vantagens.form');
	}

	/**
	 * Store a newly created resource in storage.
	 *
	 * @return Response
	 */
	public function store()
	{
		$object = new Vantagens;

		$object->frase_principal = Input::get('frase_principal');
		$object->frase_secundaria = Input::get('frase_secundaria');
		$object->feature1 = Input::get('feature1');
		$object->feature2 = Input::get('feature2');
		$object->feature3 = Input::get('feature3');
		$object->feature4 = Input::get('feature4');
		$object->feature5 = Input::get('feature5');
		$object->feature6 = Input::get('feature6');
		
		if($this->limiteInsercao && sizeof( Vantagens::all() ) >= $this->limiteInsercao)
			return Redirect::back()->withErrors(array('Número máximo de Registros atingido!'));

		
		try {

			$object->save();

			Session::flash('sucesso', true);
			Session::flash('mensagem', 'Texto criado com sucesso.');
			return Redirect::route('painel.vantagens.index');

		} catch (\Exception $e) {

			Session::flash('formulario', Input::all());
			return Redirect::back()->withErrors(array('Erro ao criar Texto!'));	

		}		
	}

	/**
	 * Display the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function show($id)
	{
	}

	/**
	 * Show the form for editing the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function edit($id)
	{
		$this->layout->content = View::make('backend.vantagens.edit')->with('registro', Vantagens::find($id));
	}

	/**
	 * Update the specified resource in storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function update($id)
	{
		$object = Vantagens::find($id);

		$object->frase_principal = Input::get('frase_principal');
		$object->frase_secundaria = Input::get('frase_secundaria');
		$object->feature1 = Input::get('feature1');
		$object->feature2 = Input::get('feature2');
		$object->feature3 = Input::get('feature3');
		$object->feature4 = Input::get('feature4');
		$object->feature5 = Input::get('feature5');
		$object->feature6 = Input::get('feature6');
		
		try {

			$object->save();
			Session::flash('sucesso', true);
			Session::flash('mensagem', 'Texto alterado com sucesso.');
			return Redirect::route('painel.vantagens.index');

		} catch (\Exception $e) {

			Session::flash('formulario', Input::all());
			return Redirect::back()->withErrors(array('Erro ao criar Texto!'));

		}
	}

	/**
	 * Remove the specified resource from storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function destroy($id)
	{
		$object = Vantagens::find($id);
		$object->delete();

		Session::flash('sucesso', true);
		Session::flash('mensagem', 'Texto removido com sucesso.');

		return Redirect::route('painel.vantagens.index');
	}

}

laravel/app/views/backend/vantagens/edit.blade.php
@section('conteudo')

    <div class="container add">

      	<h2>
        	Editar Texto
        </h2>  

		{{ Form::open( array('route' => array('painel.vantagens.update', $registro->id), 'files' => true, 'method' => 'put') ) }}
			<div class="pad">

		    	@if(Session::has('sucesso'))
		    	   <div class="alert alert-block alert-success"><button type="button" class="close" data-dismiss="alert">&times;</button>{{ Session::get('mensagem') }}</div>
		        @endif

		    	@if($errors->any())
		    		<div class="alert alert-block alert-danger"><button type="button" class="close" data-dismiss="alert">&times;</button>{{ $errors->first() }}</div>
		    	@endif	


				<div class="form-group">
					<label for="inputFrasePrincipal">Frase Principal</label>
					<input type="text" name="frase_principal" class="form-control" id="inputFrasePrincipal" value="{{$registro->frase_principal }}">
				</div>
				
				<div class="form-group">
					<label for="inputFraseSecundária">Frase Secundária</label>
					<input type="text" name="frase_secundaria" class="form-control" id="inputFraseSecundária" value="{{$registro->frase_secundaria }}">
				</div>

				<div class="well">
					<div class="form-group">
						<div style="width:62px; height:62px; margin-bottom:5px; border:1px #ddd solid; background: url(assets/img/geral-s74653a7d7b.png) -60px -249px no-repeat;"></div>
						<label for="inputFeature1">Texto para Feature 1</label>
						<input type="text" name="feature1" class="form-control" id="inputFeature1" value="{{$registro->feature1}}">
					</div>
				</div>
				
				<div class="well">
					<div class="form-group">
						<div style="width:62px; height:62px; margin-bottom:5px; border:1px #ddd solid; background: url(assets/img/geral-s74653a7d7b.png) 0 -189px no-repeat;"></div>
						<label for="inputFeature2">Texto para Feature 2</label>
						<input type="text" name="feature2" class="form-control" id="inputFeature2" value="{{$registro->feature2}}">
					</div>
				</div>
				
				<div class="well">
					<div class="form-group">
						<div style="width:62px; height:62px; margin-bottom:5px; border:1px #ddd solid; background: url(assets/img/geral-s74653a7d7b.png) -60px -189px no-repeat;"></div>
						<label for="inputFeature3">Texto para Feature 3</label>
						<input type="text" name="feature3" class="form-control" id="inputFeature3" value="{{$registro->feature3}}">
					</div>
				</div>

				<div class="well">
					<div class="form-group">
						<div style="width:62px; height:62px; margin-bottom:5px; border:1px #ddd solid; background: url(assets/img/geral-s74653a7d7b.png) -120px -189px no-repeat;"></div>
						<label for="inputFeature4">Texto para Feature 4</label>
						<input type="text" name="feature4" class="form-control" id="inputFeature4" value="{{$registro->feature4}}">
					</div>
				</div>
				
				<div class="well">
					<div class="form-group">
						<div style="width:62px; height:62px; margin-bottom:5px; border:1px #ddd solid; background: url(assets/img/geral-s74653a7d7b.png) 0 -249px no-repeat;"></div>
						<label for="inputFeature5">Texto para Feature 5</label>
						<input type="text" name="feature5" class="form-control" id="inputFeature5" value="{{$registro->feature5}}">
					</div>
				</div>

				<div class="well">
					<div class="form-group">
						<div style="width:62px; height:62px; margin-bottom:5px; border:1px #ddd solid; background: url(assets/img/geral-s74653a7d7b.png) -120px -249px no-repeat;"></div>
						<label for="inputFeature 6">Texto para Feature 6</label>
						<input type="text" name="feature6" class="form-control" id="inputFeature6" value="{{$registro->feature6}}">
					</div>
				</div>

				<button type="submit" title="Salvar" class="btn btn-success">Salvar</button>

				<a href="{{URL::route('painel.vantagens.index')}}" title="Voltar" class="btn btn-default btn-voltar">Voltar</a>

			</div>
		</form>
    </div>
    
@stop

laravel/app/views/backend/vantagens/form.blade.php
@section('conteudo')

    <div class="container add">

      	<h2>
        	Adicionar Texto
        </h2>  

		<form action="{{URL::route('painel.vantagens.store')}}" method="post" enctype="multipart/form-data">
			<div class="pad">

		    	@if(Session::has('sucesso'))
		    	   <div class="alert alert-block alert-success"><button type="button" class="close" data-dismiss="alert">&times;</button>{{ Session::get('mensagem') }}</div>
		        @endif

		    	@if($errors->any())
		    		<div class="alert alert-block alert-danger"><button type="button" class="close" data-dismiss="alert">&times;</button>{{ $errors->first() }}</div>
		    	@endif


				<div class="form-group">
					<label for="inputFrase Principal">Frase Principal</label>
					<textarea name="frase_principal" class="form-control" id="inputFrase Principal" >@if(Session::has('formulario')) {{ $s=Session::get('formulario'); echo $s['frase_principal'] }} @endif</textarea>
				</div>
				
				<div class="form-group">
					<label for="inputFrase Secundária">Frase Secundária</label>
					<textarea name="frase_secundaria" class="form-control" id="inputFrase Secundária" >@if(Session::has('formulario')) {{ $s=Session::get('formulario'); echo $s['frase_secundaria'] }} @endif</textarea>
				</div>
				
				<div class="form-group">
					<label for="inputFeature 1">Feature 1</label>
					<textarea name="feature1" class="form-control" id="inputFeature 1" >@if(Session::has('formulario')) {{ $s=Session::get('formulario'); echo $s['feature1'] }} @endif</textarea>
				</div>

				<div class="form-group">
					<label for="inputFeature 2">Feature 2</label>
					<textarea name="feature2" class="form-control" id="inputFeature 2" >@if(Session::has('formulario')) {{ $s=Session::get('formulario'); echo $s['feature2'] }} @endif</textarea>
				</div>

				<div class="form-group">
					<label for="inputFeature 3">Feature 3</label>
					<textarea name="feature3" class="form-control" id="inputFeature 3" >@if(Session::has('formulario')) {{ $s=Session::get('formulario'); echo $s['feature3'] }} @endif</textarea>
				</div>

				<div class="form-group">
					<label for="inputFeature 4">Feature 4</label>
					<textarea name="feature4" class="form-control" id="inputFeature 4" >@if(Session::has('formulario')) {{ $s=Session::get('formulario'); echo $s['feature4'] }} @endif</textarea>
				</div>

				<div class="form-group">
					<label for="inputFeature 5">Feature 5</label>
					<textarea name="feature5" class="form-control" id="inputFeature 5" >@if(Session::has('formulario')) {{ $s=Session::get('formulario'); echo $s['feature5'] }} @endif</textarea>
				</div>

				<div class="form-group">
					<label for="inputFeature 6">Feature 6</label>
					<textarea name="feature6" class="form-control" id="inputFeature 6" >@if(Session::has('formulario')) {{ $s=Session::get('formulario'); echo $s['feature6'] }} @endif</textarea>
				</div>

				<button type="submit" title="Inserir" class="btn btn-success">Inserir</button>

				<a href="{{URL::route('painel.vantagens.index')}}" title="Voltar" class="btn btn-default btn-voltar">Voltar</a>

			</div>
		</form>
    </div>
    
@stop

laravel/app/views/backend/vantagens/index.blade.php
@section('conteudo')

<div class="container">

    @if(Session::has('sucesso'))
        <div class="alert alert-block alert-success"><button type="button" class="close" data-dismiss="alert">&times;</button>{{ Session::get('mensagem') }}</div>
    @endif

    @if($errors->any())
        <div class="alert alert-block alert-danger"><button type="button" class="close" data-dismiss="alert">&times;</button>{{ $errors->first() }}</div>
    @endif

    <h2>
        Vantagens 
    </h2>

    <table class='table table-striped table-bordered table-hover'>

        <thead>
            <tr>
                <th>Frase Principal</th>
				<th>Frase Secundária</th>
                <th><span class="glyphicon glyphicon-cog"></span></th>
            </tr>
        </thead>

        <tbody>
        @foreach ($registros as $registro)

            <tr class="tr-row" id="row_{{ $registro->id }}">
                <td>{{ Str::words(strip_tags($registro->frase_principal), 15) }}</td>
				<td>{{ Str::words(strip_tags($registro->frase_secundaria), 15) }}</td>
                <td class="crud-actions">
                    <a href='{{ URL::route('painel.vantagens.edit', $registro->id ) }}' class='btn btn-primary btn-sm'>editar</a>                    
                </td>
            </tr>

        @endforeach
        </tbody>

    </table>

    
</div>

@stop