laravel/app/routes.php
<?php

Route::any('/', array('as' => 'home', 'uses' => 'HomeController@index'));
Route::any('home', array('as' => 'home', 'uses' => 'HomeController@index'));
Route::any('comerciante', array('as' => 'comerciante', 'uses' => 'HomeController@comerciante'));
Route::any('termos-de-uso', array('as' => 'termos', 'uses' => 'HomeController@termosDeUso'));
Route::post('enviaContatoVisitantes', array('as' => 'contato.visitantes', 'uses' => 'HomeController@enviaContatoVisitantes'));
Route::post('enviaContatoEmpresa', array('as' => 'contato.empresas', 'uses' => 'HomeController@enviaContatoEmpresa'));
Route::post('cadastraNewsletter', array('as' => 'cadastro.newsletter', 'uses' => 'HomeController@cadastraNewsletter'));

Route::get('painel', array('before' => 'auth', 'as' => 'painel.home', 'uses' => 'Painel\HomeController@index'));
Route::get('painel/login', array('as' => 'painel.login', 'uses' => 'Painel\HomeController@login'));

// Autenticação do Login
Route::post('painel/login',  array('as' => 'painel.auth', function(){
	$authvars = array(
		'username' => Input::get('username'),
		'password' => Input::get('password')
	);

	$lembrar = (Input::get('lembrar') == '1') ? true : false;

	if(Auth::attempt($authvars, $lembrar)){
		return Redirect::to('painel');
	}else{
		Session::flash('login_errors', true);
		return Redirect::to('painel/login');
	}
}));

Route::get('painel/logout', array('as' => 'painel.off', function(){
	Auth::logout();
	return Redirect::to('painel');
}));

Route::post('ajax/gravaOrdem', array('before' => 'auth', 'uses' => 'Painel\AjaxController@gravaOrdem'));

Route::group(array('prefix' => 'painel', 'before' => 'auth'), function()
{

    Route::get('download', function(){

    	$filename = 'cadastros_'.date('d-m-Y-H-i-s');

		Excel::create($filename, function($excel) {
		    $excel->sheet('Usuários Cadastrados', function($sheet) {
		        $sheet->fromModel(\CadastrosNewsletter::select('nome', 'email')->orderBy('nome')->get());
		    });
		})->download('csv');
    });
    	
    Route::resource('usuarios', 'Painel\UsuariosController');
    Route::resource('banner', 'Painel\BannerController');
	Route::resource('sobre', 'Painel\SobreController');
	Route::resource('comofunciona', 'Painel\ComoFuncionaController');
	Route::resource('vantagens', 'Painel\VantagensController');
	Route::resource('comerciante', 'Painel\ComercianteController');
	Route::resource('pelasuaempresa', 'Painel\PelaSuaEmpresaController');
	Route::resource('pelasuaempresavantagens', 'Painel\PelaSuaEmpresaVantagensController');
	Route::resource('contato', 'Painel\ContatoController');
	Route::resource('termosdeuso', 'Painel\TermosDeUsoController');
	Route::resource('contatosvisitantes', 'Painel\ContatosVisitantesController');
	Route::resource('contatosempresas', 'Painel\ContatosEmpresasController');
	Route::resource('cadastrosnewsletter', 'Painel\CadastrosNewsletterController');
	Route::resource('seo', 'Painel\SEOController');
	Route::resource('links', 'Painel\LinksController');
	//NOVASROTASDOPAINEL//
});

laravel/app/models/TermosDeUso.php
<?php

class TermosDeUso extends Eloquent
{

	/**
	 * The database table used by the model.
	 *
	 * @var string
	 */
	protected $table = 'termos_de_uso';

	/**
	 * The attributes excluded from the model's JSON form.
	 *
	 * @var array
	 */
	protected $hidden = array();

	// array of attributes we CAN set on the backend
    protected $fillable = array('', 'created_at', 'updated_at');

    // and those we CAN'T set on the backend
    protected $guarded = array('id');

}

laravel/app/controllers/painel/TermosDeUsoController.php
<?php

namespace Painel;

use \View, \Input, \Str, \Session, \Redirect, \Hash, \Thumb, \Tools, \File, TermosDeUso;

class TermosDeUsoController extends BaseAdminController {

	protected $layout = 'backend.templates.index';

	protected $limiteInsercao = '1';

	/**
	 * Display a listing of the resource.
	 *
	 * @return Response
	 */
	public function index()
	{
		$this->layout->content = View::make('backend.termosdeuso.index')->with('registros', TermosDeUso::all())->with('limiteInsercao', $this->limiteInsercao);		
	}

	/**
	 * Show the form for creating a new resource.
	 *
	 * @return Response
	 */
	public function create()
	{
		$this->layout->content = View::make('backend.termosdeuso.form');
	}

	/**
	 * Store a newly created resource in storage.
	 *
	 * @return Response
	 */
	public function store()
	{
		$object = new TermosDeUso;

		$object->texto_coluna_esq = Input::get('texto_coluna_esq');
		$object->texto_coluna_dir = Input::get('texto_coluna_dir');

		if($this->limiteInsercao && sizeof( TermosDeUso::all() ) >= $this->limiteInsercao)
			return Redirect::back()->withErrors(array('Número máximo de Registros atingido!'));

		
		try {

			$object->save();

			Session::flash('sucesso', true);
			Session::flash('mensagem', 'Texto criado com sucesso.');
			return Redirect::route('painel.termosdeuso.index');

		} catch (\Exception $e) {

			Session::flash('formulario', Input::all());
			return Redirect::back()->withErrors(array('Erro ao criar Texto!'));	

		}		
	}

	/**
	 * Display the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function show($id)
	{
	}

	/**
	 * Show the form for editing the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function edit($id)
	{
		$this->layout->content = View::make('backend.termosdeuso.edit')->with('registro', TermosDeUso::find($id));
	}

	/**
	 * Update the specified resource in storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function update($id)
	{
		$object = TermosDeUso::find($id);

		$object->texto_coluna_esq = Input::get('texto_coluna_esq');
		$object->texto_coluna_dir = Input::get('texto_coluna_dir');

		try {

			$object->save();
			Session::flash('sucesso', true);
			Session::flash('mensagem', 'Texto alterado com sucesso.');
			return Redirect::route('painel.termosdeuso.index');

		} catch (\Exception $e) {

			Session::flash('formulario', Input::all());
			return Redirect::back()->withErrors(array('Erro ao criar Texto!'));

		}
	}

	/**
	 * Remove the specified resource from storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function destroy($id)
	{
		$object = TermosDeUso::find($id);
		$object->delete();

		Session::flash('sucesso', true);
		Session::flash('mensagem', 'Texto removido com sucesso.');

		return Redirect::route('painel.termosdeuso.index');
	}

}

laravel/app/views/backend/termosdeuso/edit.blade.php
@section('conteudo')

    <div class="container add">

      	<h2>
        	Editar Texto
        </h2>  

		{{ Form::open( array('route' => array('painel.termosdeuso.update', $registro->id), 'files' => true, 'method' => 'put') ) }}
			<div class="pad">

		    	@if(Session::has('sucesso'))
		    	   <div class="alert alert-block alert-success"><button type="button" class="close" data-dismiss="alert">&times;</button>{{ Session::get('mensagem') }}</div>
		        @endif

		    	@if($errors->any())
		    		<div class="alert alert-block alert-danger"><button type="button" class="close" data-dismiss="alert">&times;</button>{{ $errors->first() }}</div>
		    	@endif	


				<div class="form-group">
					<label for="inputTextoE">Texto (Coluna Esquerda)</label>
					<textarea name="texto_coluna_esq" class="form-control" id="inputTextoE" >{{$registro->texto_coluna_esq }}</textarea>
				</div>
				
				<div class="form-group">
					<label for="inputTextoD">Texto (Coluna Direita)</label>
					<textarea name="texto_coluna_dir" class="form-control" id="inputTextoD" >{{$registro->texto_coluna_dir }}</textarea>
				</div>

				<button type="submit" title="Salvar" class="btn btn-success">Salvar</button>

				<a href="{{URL::route('painel.termosdeuso.index')}}" title="Voltar" class="btn btn-default btn-voltar">Voltar</a>

			</div>
		</form>
    </div>
    
@stop

laravel/app/views/backend/termosdeuso/form.blade.php
@section('conteudo')

    <div class="container add">

      	<h2>
        	Adicionar Texto
        </h2>  

		<form action="{{URL::route('painel.termosdeuso.store')}}" method="post" enctype="multipart/form-data">
			<div class="pad">

		    	@if(Session::has('sucesso'))
		    	   <div class="alert alert-block alert-success"><button type="button" class="close" data-dismiss="alert">&times;</button>{{ Session::get('mensagem') }}</div>
		        @endif

		    	@if($errors->any())
		    		<div class="alert alert-block alert-danger"><button type="button" class="close" data-dismiss="alert">&times;</button>{{ $errors->first() }}</div>
		    	@endif


				<div class="form-group">
					<label for="inputTexto">Texto</label>
					<textarea name="texto" class="form-control" id="inputTexto" >@if(Session::has('formulario')) {{ $s=Session::get('formulario'); echo $s['texto'] }} @endif</textarea>
				</div>
				

				<button type="submit" title="Inserir" class="btn btn-success">Inserir</button>

				<a href="{{URL::route('painel.termosdeuso.index')}}" title="Voltar" class="btn btn-default btn-voltar">Voltar</a>

			</div>
		</form>
    </div>
    
@stop

laravel/app/views/backend/termosdeuso/index.blade.php
@section('conteudo')

<div class="container">

    @if(Session::has('sucesso'))
        <div class="alert alert-block alert-success"><button type="button" class="close" data-dismiss="alert">&times;</button>{{ Session::get('mensagem') }}</div>
    @endif

    @if($errors->any())
        <div class="alert alert-block alert-danger"><button type="button" class="close" data-dismiss="alert">&times;</button>{{ $errors->first() }}</div>
    @endif

    <h2>
        Termos De Uso 
    </h2>

    <table class='table table-striped table-bordered table-hover'>

        <thead>
            <tr>
                <th>Texto (Coluna Esquerda)</th>
                <th>Texto (Coluna Direita)</th>
                <th><span class="glyphicon glyphicon-cog"></span></th>
            </tr>
        </thead>

        <tbody>
        @foreach ($registros as $registro)

            <tr class="tr-row" id="row_{{ $registro->id }}">
                <td>{{ Str::words(strip_tags($registro->texto_coluna_esq), 15) }}</td>
                <td>{{ Str::words(strip_tags($registro->texto_coluna_dir), 15) }}</td>
                <td class="crud-actions">
                    <a href='{{ URL::route('painel.termosdeuso.edit', $registro->id ) }}' class='btn btn-primary btn-sm'>editar</a>                    
                </td>
            </tr>

        @endforeach
        </tbody>

    </table>

    
</div>

@stop